In [1]:
print("he;;p:")

he;;p:


In [1]:
print("helllo")

helllo


In [4]:
pip install numpy 

In [ ]:
import numpy as np


In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a=([1,2,3,4,5,"hello"])
a

[1, 2, 3, 4, 5]

In [7]:
np.array(a)

array([1, 2, 3, 4, 5])

In [8]:
np.array(a)

array([1, 2, 3, 4, 5])

In [ ]:
# using the vector in the numpy 

In [9]:
l=([1,2,3],[4,5,6],[7,6,5])
l

([1, 2, 3], [4, 5, 6], [7, 6, 5])

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 5]])

In [ ]:
# we can add more array are callled tensores

In [49]:
#arry generation funtion 

In [50]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [52]:

arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [53]:
arr=np.array((4,4))
arr

array([4, 4])

In [54]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [55]:
arr=np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
 # we are using the linspace in the numpy
# use the linspace instead of array 

In [57]:
a=np.linspace(1,5,3)
a
# this is using of linear space in the numpy

array([1., 3., 5.])

In [58]:
# use the randome generation function in python 
# we can use the randome library

In [59]:
e=np.random.rand(10) # it is also a vector 
e

array([0.61614712, 0.91001014, 0.55719462, 0.95598921, 0.59233012,
       0.62405148, 0.57298378, 0.73260199, 0.73685333, 0.17195125])

In [60]:
np.random.rand(10)

array([0.88425684, 0.83804906, 0.55836838, 0.68688364, 0.35921132,
       0.05547525, 0.61983996, 0.72782565, 0.19931872, 0.38406334])

In [61]:


np.random.rand(3)

array([0.1366281 , 0.880854  , 0.72967574])



np.random.randn(10,20,10)

In [34]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9,]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# Adding the attribute
arr.shape

(3, 3)

In [36]:
 arr.size

9

In [38]:
arr.dtype

dtype('int32')

In [ ]:
# using the array method


In [40]:
arr.min()

1

In [42]:
arr.sum()

45

In [43]:
arr.min()

1

In [44]:
arr.max()

9

In [45]:
np.sum(arr,axis=0)


array([12, 15, 18])

In [46]:
arr.mean()

5.0

In [47]:
arr.std()

2.581988897471611

In [48]:
arr.argmax()

8

In [49]:
arr.argmin()

0

In [50]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
# use to reshape the array 
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [53]:
# using the indexing in the numpy
import numpy as np

In [55]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [61]:
arr[6]

17

In [62]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
arr[3:9]

array([14, 15, 16, 17, 18, 19])

In [64]:
arr[3::2]

array([14, 16, 18, 20])

In [66]:
arr=np.arange(1,31).reshape(6,5)# fist is the row and second is column 
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [80]:
arr[0:2,1:3] # indexing /slicing = 2,7/2,8

array([[2, 3],
       [7, 8]])

arr[4::5,4::6]

In [82]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [85]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
# boolean indexing 

In [89]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
 # we want all number is even 

In [90]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [91]:
bool=arr%1==0
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [1]:
import numpy as np
#lets creat an array 
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
import numpy as np

In [7]:
l=[[1,3,4],[4,6,3],[5,9,8]]
l

[[1, 3, 4], [4, 6, 3], [5, 9, 8]]

In [8]:
np.array(l)

array([[1, 3, 4],
       [4, 6, 3],
       [5, 9, 8]])

In [9]:
# lets creat an array with arang  function instead of using for loop

In [11]:
a=np.arange(1,11,2)
a # the array is created from 1 to 10 

array([1, 3, 5, 7, 9])

In [15]:
arr=np.zeros((6,6))

In [16]:
arr # it show six rows and six columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr=np.ones((8,4))

In [18]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# using the linspace as a linear spacing it is help to make the space in the array.

In [22]:
a=np.linspace(1,5,100)
a

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [ ]:
ramdome number generation

In [24]:
a=np.random.rand(1) # tis is a vectore one braces for vectore and 2 breaces for matrix
a

array([0.26510154])

In [30]:
b=np.random.randn(10)
b

array([ 0.5236154 , -0.45406529, -0.54503618, -0.98235413,  0.18318329,
       -0.84653319, -0.96153068, -0.3453672 ,  0.36576542, -0.00799836])

In [ ]:
# generate the random integer

In [34]:
np.random.randint(10,20,10)

array([11, 13, 19, 17, 12, 11, 19, 14, 11, 16])

In [35]:
ARRAY ATTRIBUTE

SyntaxError: invalid syntax (1518353429.py, line 1)

In [37]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
c.shape

(3, 3)

In [40]:
c.size

9

In [41]:
c.dtype

dtype('int32')

# these are the basic attribnute in the array 

ARRAY METHOD ARE: MIN AND MAX

In [42]:
c.min()

1

In [65]:
c.max()

9

In [66]:
# sum of the array

In [67]:
np.sum(c,axis=0)


array([12, 15, 18])

In [72]:
#RESHAPING THE ARRAY # IGNORE COMMENT 

In [74]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
a.mean()

4.0

In [89]:
a.std()

2.581988897471611

In [90]:
a.argmax()

8

In [91]:
a.argmin()

0

In [95]:
arr=np.arange(1,41)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [96]:
arr.reshape(8,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [97]:
#using the reshape function in the numpy 

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [99]:
arr.reshape(5,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [100]:
ARRAY INDEXING

SyntaxError: invalid syntax (56646722.py, line 1)

In [ ]:
import numpy as np 

In [102]:
a=np.arange(12)

In [103]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
arr[6]

7

In [108]:
arr[3::2]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40])

In [110]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [128]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [136]:
slice=arr[3:6,3:6]
slice # selecting the randome digit in the array 

array([[19, 20],
       [24, 25],
       [29, 30]])

In [137]:
#BOOLEAN INDEXING 

In [138]:
arr=np.arange(10,100)

In [146]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [147]:
bool_index=arr%2==0
bool_index

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [148]:
arr=arr[bool_index]
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [149]:
# ARRAY OPERATION

In [ ]:
AIRTHMETIC OPERATION

In [151]:
import numpy as np

In [153]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [154]:
 a1*a2

array([ 6, 14, 24, 36, 50])

In [155]:
a1-a2

array([-5, -5, -5, -5, -5])

In [2]:
NUMPY INDEXING AND SLICING OF VECTORS|

SyntaxError: invalid syntax (2479350210.py, line 1)

In [3]:
# Assistant
# NUMPY INDEXING AND SLICING OF VECTORS
# This section will cover how to access elements in NumPy arrays
# through indexing and slicing operations, which allow for efficient
# data manipulation and extraction of subarrays

In [4]:
# Assistant
# NUMPY INDEXING AND SLICING OF VECTORS
# This section will cover how to access elements in NumPy arrays
# through indexing and slicing operations, which allow for efficient
# data manipulation and extraction of subarrays

In [6]:
import numpy as np

In [7]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[1:4]

array([12, 13, 14])

In [12]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

arr[3::5]

In [ ]:
SLICING THE MATRIC IN THE NUMPY 

In [14]:
import numpy as np
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[0,4]

5

In [16]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [18]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [19]:
arr[2:5,3:]


array([[14, 15],
       [19, 20],
       [24, 25]])

In [20]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [21]:
BOOLEAN INDEXING 

SyntaxError: invalid syntax (1914363284.py, line 1)

In [31]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [32]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [33]:
c=arr[bool_index]
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

ARITHMATIC OPERATIONS

In [37]:
a1=np.array([1,2,3,4,5])
a2=np.array([2,3,4,5,6])
a1+a2


array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])

In [38]:
a1-a2

array([-1, -1, -1, -1, -1])

In [39]:
a1/a2

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])

In [40]:
a1*a2

array([ 2,  6, 12, 20, 30])

In [41]:
a1%a1

array([0, 0, 0, 0, 0])

BROADCASATING

In [42]:
L=[12,21,12,32,43,65]
arr=np.array(L)

In [47]:
arr+10

array([22, 31, 22, 42, 53, 75])

DEEP AND SHALLOW COPYING 

In [48]:
a2=np.arange(1,26).reshape(5,5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
a2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

deep and shallow coping 

In [50]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
slice=a[:5]
slice=slice*7
slice

array([ 7, 14, 21, 28, 35])

In [8]:
import numpy as np
a=np.array([1,2,2,2,2,2])
a

array([1, 2, 2, 2, 2, 2])