Cheak Whether a numpy array cantains a specified row

SQUEEZ IS UTILIZE TO REMOVAL OF SINGLE_DIMENSIONAL ELEMENT FROM THE SHAPE OF A NUMPY ARRAY

import numpy as np
arrr=np.array([[1,2,3],
              [4,5,6,]])
row=[4,5,6]
print(row in arrr.tolist())


In [7]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

print("Array:\n", arr)
print([1, 2, 3, 4, 5] in arr.tolist())     
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())    
print([11, 12, 13, 14, 15] in arr.tolist())

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


 Example 2 :
 suppose you have a dataset of the student, and you want to cheak the particular record of the studnet 

In [14]:
student_makrs=np.array([[85,90,92],
                       [70,67,80],
                       [95,68,91]])
Student = [70,65,80]
print(Student in student_makrs.tolist())

False


Remove single dimentional array in the shape of  array
using numpy.squeeze(arr,axis=None)  

In [17]:
import numpy as np
int_arr=np.array([[[2,2,2,],[3,4,5]]])
print("Input array:",int_arr)
print("shape of input array:",int_arr.shape)
out_arr=np.squeeze(int_arr)
print("output squeezs array:",out_arr)
print("Shape of output array:",out_arr.shape)

Input array: [[[2 2 2]
  [3 4 5]]]
shape of input array: (1, 2, 3)
output squeezs array: [[2 2 2]
 [3 4 5]]
Shape of output array: (2, 3)


Example 1: Using the axis parameter to squeez a specific dimension

In [21]:
import numpy as np
in_arr=np.arange(9).reshape(1,3,3)
print("Input array",in_arr)
out_array=np.squeeze(in_arr,axis=0)
print("out array:",out_arr)
print("The shapes of input and output array:")
print(in_arr.shape,out_arr.shape)

Input array [[[0 1 2]
  [3 4 5]
  [6 7 8]]]
out array: [[2 2 2]
 [3 4 5]]
The shapes of input and output array:
(1, 3, 3) (2, 3)


 Example 3: ERROR When trying to squeez a non-singleton dimention

In [26]:
import numpy as np
in_arr=np.arange(9).reshape(1,3,3)
print("input array:",in_arr)
# i try to squeez the axis that does'nt have size 1
try:
    out_arr=np.squeeze(in_arr,axis=1)
except ValueError as e:
    print("Error:",e)


input array: [[[0 1 2]
  [3 4 5]
  [6 7 8]]]
Error: cannot select an axis to squeeze out which has size not equal to one


In [1]:
import numpy as np
arr=np.array([[2,4,7,9],
              [4,5,6,7],
              [6,4,7,2],
              [6,8,9,2]])
seq=np.array([6,7])
k=seq.size
sl=np.lib.stride_tricks.sliding_window_view(arr,k,axis=1)
out=np.sum(np.all(sl==seq, axis=2))
print(out)

1


Using the string conversion and count

In [ ]:
# convert entire array into the string and cheak how many time the sequence pattern appears inside the 
#string

In [2]:
import numpy as np
arr=([[2,9,8,7],
      [9,8,7,6], 
      [3,4,9,8],
      [7,8,9,8]])
out=repr(arr).count("9,8") # repr(arr) converts the array into a formatted text
print(out)

0


using row wise conversion and cutting 

In [3]:
import numpy as np
arr=([[2,9,8,7],
      [9,8,7,6], 
      [3,4,9,8],
      [7,8,9,8]])
seq="9,8"
our=sum(" ".join(map(str,r)).count(seq) for r in arr)
print(out)

0
