In [ ]:
NUMPY EXCERCISES
import numpy as np

In [25]:
import numpy as np
S=np.array([
    [2,4,5,6,7,4,4,3,5],
    [4,3,4,5,6,7,8,6,5],
    [2,3,4,5,6,3,4,5,6],

    [4,5,6,7,8,2,3,3,6],
    [2,3,4,9,8,7,4,5,1],
    [1,3,5,7,9,0,2,4,6],

    [1,2,3,1,2,3,4,5,6],
    [3,4,5,6,4,5,6,3,2],
    [4,5,6,3,4,5,2,3,1]
])

In [23]:
b=np.sum(S,axis=1)
for i in b:
    if i!=45:
        print("the sudoku is valid:")
    else:
        print("false,the sudoku is not valid ")

the sudoku is valid:
the sudoku is valid:
the sudoku is valid:
the sudoku is valid:
the sudoku is valid:
the sudoku is valid:
the sudoku is valid:
the sudoku is valid:
the sudoku is valid:


In [27]:
S[0:3,0:3]

array([[2, 4, 5],
       [4, 3, 4],
       [2, 3, 4]])

In [29]:
S[0:3,3:6]

array([[6, 7, 4],
       [5, 6, 7],
       [5, 6, 3]])

In [30]:
S[0:3,6:9]

array([[4, 3, 5],
       [8, 6, 5],
       [4, 5, 6]])

In [37]:
 for i in range(0,9,3):
     for j in range(0,9,3):
         n=(S[i:i+3,j:j+3])
         print(n.sum())

31
49
46
33
57
34
33
33
32


In [7]:
import numpy as np
# colummn : Age ,math marks,science mark
data=np.array([
    [18,85,78], # student 1
    [19,92,88], # student 2 # 1s column 
    [20,78,65], # student 3
    [19,76,89], # student 4
    [12,87,96]  # student 5
])

In [38]:
# get the shape of the matrix 
data.shape

(5, 3)

In [45]:
# find the average age of student 
np.mean(data[:,0])

np.float64(17.6)

In [47]:
# extracts maths marks of all student
data[:,1]

array([85, 92, 78, 76, 87])

In [48]:
# find the highest science marks
np.max(data[:,2])

np.int64(96)

In [50]:
# Get the detail pf the student who scored more than 90 in maths 
# using boolean
data[data[:,1] > 90]



array([[19, 92, 88]])

In [57]:
# increase maths marks by 5 
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [20, 83, 65],
       [19, 81, 89],
       [12, 92, 96]])

In [64]:
# find how many stundent is younger than 19 
len(data[data[:,0]<19])


2

In [65]:
# calculate the average marks in each subject 
np.mean(data[:,1:],axis=0)


array([88.6, 83.2])

In [77]:
# get data of student at least 80 i two subject
data[(data[:,1]>=80) & (data[:,2])>=80]


array([], shape=(0, 3), dtype=int64)

In [86]:
# replace all science marks <75 with 0
data[:,2][data[:,2]<75]= 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [ 0,  0,  0],
       [19, 81, 89],
       [12, 92, 96]])